# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 22:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pro_models',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mod_name', models.CharField(max_length=50)),
                ('display', models.FloatField()),
                ('processor', models.FloatField()),
                ('ram', models.FloatField()),
                ('fcam', models.FloatField()),
                ('batt_cap', models.FloatField()),
                ('price', models.FloatField()),
                ('image', models.ImageField(upload_to='')),
                ('mapid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobapp.pro_brand_map')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField()),
                ('pro_mod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobapp.Pro_models')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='add',
            field=models.TextField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobapp.Profile'),
        ),
        migrations.AddField(
            model_name='booking',
            name='pro_mod_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobapp.Pro_models'),
        ),
        migrations.AddField(
            model_name='booking',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobapp.Profile'),
        ),
    ]
